// Generated by gencpp from file interfaces/MoveRobotFeedback.msg
// DO NOT EDIT!


#ifndef INTERFACES_MESSAGE_MOVEROBOTFEEDBACK_H
#define INTERFACES_MESSAGE_MOVEROBOTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interfaces
{
template <class ContainerAllocator>
struct MoveRobotFeedback_
{
  typedef MoveRobotFeedback_<ContainerAllocator> Type;

  MoveRobotFeedback_()
    : percentage(0.0)  {
    }
  MoveRobotFeedback_(const ContainerAllocator& _alloc)
    : percentage(0.0)  {
  (void)_alloc;
    }



   typedef double _percentage_type;
  _percentage_type percentage;





  typedef boost::shared_ptr< ::interfaces::MoveRobotFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interfaces::MoveRobotFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotFeedback_

typedef ::interfaces::MoveRobotFeedback_<std::allocator<void> > MoveRobotFeedback;

typedef boost::shared_ptr< ::interfaces::MoveRobotFeedback > MoveRobotFeedbackPtr;
typedef boost::shared_ptr< ::interfaces::MoveRobotFeedback const> MoveRobotFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interfaces::MoveRobotFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interfaces::MoveRobotFeedback_<ContainerAllocator1> & lhs, const ::interfaces::MoveRobotFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage == rhs.percentage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interfaces::MoveRobotFeedback_<ContainerAllocator1> & lhs, const ::interfaces::MoveRobotFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interfaces::MoveRobotFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::MoveRobotFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::MoveRobotFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46302a97c06fe5a4416c427fe6ee8804";
  }

  static const char* value(const ::interfaces::MoveRobotFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46302a97c06fe5a4ULL;
  static const uint64_t static_value2 = 0x416c427fe6ee8804ULL;
};

template<class ContainerAllocator>
struct DataType< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interfaces/MoveRobotFeedback";
  }

  static const char* value(const ::interfaces::MoveRobotFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64 percentage\n"
"\n"
;
  }

  static const char* value(const ::interfaces::MoveRobotFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interfaces::MoveRobotFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interfaces::MoveRobotFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percentage: ";
    Printer<double>::stream(s, indent + "  ", v.percentage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACES_MESSAGE_MOVEROBOTFEEDBACK_H
