// Generated by gencpp from file interfaces/MoveRobotResult.msg
// DO NOT EDIT!


#ifndef INTERFACES_MESSAGE_MOVEROBOTRESULT_H
#define INTERFACES_MESSAGE_MOVEROBOTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interfaces
{
template <class ContainerAllocator>
struct MoveRobotResult_
{
  typedef MoveRobotResult_<ContainerAllocator> Type;

  MoveRobotResult_()
    : state()  {
    }
  MoveRobotResult_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::interfaces::MoveRobotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interfaces::MoveRobotResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotResult_

typedef ::interfaces::MoveRobotResult_<std::allocator<void> > MoveRobotResult;

typedef boost::shared_ptr< ::interfaces::MoveRobotResult > MoveRobotResultPtr;
typedef boost::shared_ptr< ::interfaces::MoveRobotResult const> MoveRobotResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interfaces::MoveRobotResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interfaces::MoveRobotResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interfaces::MoveRobotResult_<ContainerAllocator1> & lhs, const ::interfaces::MoveRobotResult_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interfaces::MoveRobotResult_<ContainerAllocator1> & lhs, const ::interfaces::MoveRobotResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interfaces::MoveRobotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interfaces::MoveRobotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::MoveRobotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interfaces::MoveRobotResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::MoveRobotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interfaces::MoveRobotResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interfaces::MoveRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af6d3a99f0fbeb66d3248fa4b3e675fb";
  }

  static const char* value(const ::interfaces::MoveRobotResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf6d3a99f0fbeb66ULL;
  static const uint64_t static_value2 = 0xd3248fa4b3e675fbULL;
};

template<class ContainerAllocator>
struct DataType< ::interfaces::MoveRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interfaces/MoveRobotResult";
  }

  static const char* value(const ::interfaces::MoveRobotResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interfaces::MoveRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"string state\n"
;
  }

  static const char* value(const ::interfaces::MoveRobotResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interfaces::MoveRobotResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interfaces::MoveRobotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interfaces::MoveRobotResult_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERFACES_MESSAGE_MOVEROBOTRESULT_H
