poker:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  arm_base_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_base
    pid: {p: 1.0, i: 0.01, d: 0.0}
 
