; Auto-generated. Do not edit!


(cl:in-package interfaces-msg)


;//! \htmlinclude MoveRobotResult.msg.html

(cl:defclass <MoveRobotResult> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:string
    :initform ""))
)

(cl:defclass MoveRobotResult (<MoveRobotResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveRobotResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveRobotResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name interfaces-msg:<MoveRobotResult> is deprecated: use interfaces-msg:MoveRobotResult instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <MoveRobotResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader interfaces-msg:state-val is deprecated.  Use interfaces-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveRobotResult>) ostream)
  "Serializes a message object of type '<MoveRobotResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'state))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'state))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveRobotResult>) istream)
  "Deserializes a message object of type '<MoveRobotResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'state) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'state) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveRobotResult>)))
  "Returns string type for a message object of type '<MoveRobotResult>"
  "interfaces/MoveRobotResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveRobotResult)))
  "Returns string type for a message object of type 'MoveRobotResult"
  "interfaces/MoveRobotResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveRobotResult>)))
  "Returns md5sum for a message object of type '<MoveRobotResult>"
  "af6d3a99f0fbeb66d3248fa4b3e675fb")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveRobotResult)))
  "Returns md5sum for a message object of type 'MoveRobotResult"
  "af6d3a99f0fbeb66d3248fa4b3e675fb")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveRobotResult>)))
  "Returns full string definition for message of type '<MoveRobotResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveRobotResult)))
  "Returns full string definition for message of type 'MoveRobotResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveRobotResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'state))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveRobotResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveRobotResult
    (cl:cons ':state (state msg))
))
