; Auto-generated. Do not edit!


(cl:in-package interfaces-msg)


;//! \htmlinclude MoveRobotFeedback.msg.html

(cl:defclass <MoveRobotFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage
    :reader percentage
    :initarg :percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass MoveRobotFeedback (<MoveRobotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveRobotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveRobotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name interfaces-msg:<MoveRobotFeedback> is deprecated: use interfaces-msg:MoveRobotFeedback instead.")))

(cl:ensure-generic-function 'percentage-val :lambda-list '(m))
(cl:defmethod percentage-val ((m <MoveRobotFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader interfaces-msg:percentage-val is deprecated.  Use interfaces-msg:percentage instead.")
  (percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveRobotFeedback>) ostream)
  "Serializes a message object of type '<MoveRobotFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveRobotFeedback>) istream)
  "Deserializes a message object of type '<MoveRobotFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveRobotFeedback>)))
  "Returns string type for a message object of type '<MoveRobotFeedback>"
  "interfaces/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveRobotFeedback)))
  "Returns string type for a message object of type 'MoveRobotFeedback"
  "interfaces/MoveRobotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns md5sum for a message object of type '<MoveRobotFeedback>"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveRobotFeedback)))
  "Returns md5sum for a message object of type 'MoveRobotFeedback"
  "46302a97c06fe5a4416c427fe6ee8804")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveRobotFeedback>)))
  "Returns full string definition for message of type '<MoveRobotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveRobotFeedback)))
  "Returns full string definition for message of type 'MoveRobotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64 percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveRobotFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveRobotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveRobotFeedback
    (cl:cons ':percentage (percentage msg))
))
