; Auto-generated. Do not edit!


(cl:in-package interfaces-msg)


;//! \htmlinclude MoveRobotGoal.msg.html

(cl:defclass <MoveRobotGoal> (roslisp-msg-protocol:ros-message)
  ((vel
    :reader vel
    :initarg :vel
    :type cl:float
    :initform 0.0)
   (deployed
    :reader deployed
    :initarg :deployed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MoveRobotGoal (<MoveRobotGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveRobotGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveRobotGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name interfaces-msg:<MoveRobotGoal> is deprecated: use interfaces-msg:MoveRobotGoal instead.")))

(cl:ensure-generic-function 'vel-val :lambda-list '(m))
(cl:defmethod vel-val ((m <MoveRobotGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader interfaces-msg:vel-val is deprecated.  Use interfaces-msg:vel instead.")
  (vel m))

(cl:ensure-generic-function 'deployed-val :lambda-list '(m))
(cl:defmethod deployed-val ((m <MoveRobotGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader interfaces-msg:deployed-val is deprecated.  Use interfaces-msg:deployed instead.")
  (deployed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveRobotGoal>) ostream)
  "Serializes a message object of type '<MoveRobotGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'vel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'deployed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveRobotGoal>) istream)
  "Deserializes a message object of type '<MoveRobotGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'vel) (roslisp-utils:decode-double-float-bits bits)))
    (cl:setf (cl:slot-value msg 'deployed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveRobotGoal>)))
  "Returns string type for a message object of type '<MoveRobotGoal>"
  "interfaces/MoveRobotGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveRobotGoal)))
  "Returns string type for a message object of type 'MoveRobotGoal"
  "interfaces/MoveRobotGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveRobotGoal>)))
  "Returns md5sum for a message object of type '<MoveRobotGoal>"
  "2870b9bf84a5843cbf44dc91dc346385")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveRobotGoal)))
  "Returns md5sum for a message object of type 'MoveRobotGoal"
  "2870b9bf84a5843cbf44dc91dc346385")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveRobotGoal>)))
  "Returns full string definition for message of type '<MoveRobotGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%float64 vel~%bool deployed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveRobotGoal)))
  "Returns full string definition for message of type 'MoveRobotGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%float64 vel~%bool deployed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveRobotGoal>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveRobotGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveRobotGoal
    (cl:cons ':vel (vel msg))
    (cl:cons ':deployed (deployed msg))
))
